--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 12/6/2023 12:04:06 AM
-- Server version: 8.0.31
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS `ecommerce.payment`;

CREATE DATABASE IF NOT EXISTS `ecommerce.payment`
CHARACTER SET utf8mb4
COLLATE utf8mb4_general_ci;

--
-- Set default database
--
USE `ecommerce.payment`;

--
-- Create table `payment_method`
--
CREATE TABLE IF NOT EXISTS payment_method (
  ID int NOT NULL AUTO_INCREMENT,
  Name varchar(250) NOT NULL,
  Uri varchar(500) DEFAULT NULL,
  CreatedDate datetime DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  CreatedBy varchar(250) DEFAULT NULL,
  ModifiedBy varchar(250) DEFAULT NULL,
  ThumbnailImage varchar(255) DEFAULT NULL,
  PaymentMethodCode char(50) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create table `payment`
--
CREATE TABLE IF NOT EXISTS payment (
  ID int NOT NULL AUTO_INCREMENT,
  UserID char(36) DEFAULT NULL,
  OrderID int NOT NULL,
  CreatedDate datetime DEFAULT NULL,
  CreatedBy varchar(250) DEFAULT NULL,
  ModifiedDate datetime DEFAULT NULL,
  ModifiedBy varchar(250) DEFAULT NULL,
  Status int DEFAULT NULL,
  PaymentMethodID int NOT NULL,
  Total decimal(12, 2) DEFAULT NULL,
  PRIMARY KEY (ID)
)
ENGINE = INNODB,
AUTO_INCREMENT = 186,
AVG_ROW_LENGTH = 98,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create foreign key
--
ALTER TABLE payment
ADD CONSTRAINT FKPayment174483 FOREIGN KEY (PaymentMethodID)
REFERENCES payment_method (ID);

-- 
-- Dumping data for table payment_method
--
INSERT INTO payment_method VALUES
(1, 'Thanh toán khi nhận hàng', '', '2023-11-04 11:14:41', '2023-11-04 11:14:41', '', '', NULL, NULL),
(2, 'Stripe', '', '2023-11-04 11:14:41', '2023-11-04 11:14:41', '', '', NULL, NULL),
(3, 'Paypal', '', '2023-11-04 11:14:41', '2023-11-04 11:14:41', '', '', NULL, NULL),
(4, 'VNPay', '', '2023-11-04 11:14:41', '2023-11-04 11:14:41', '', '', NULL, NULL),
(5, 'Momo', '', '2023-11-04 11:14:41', '2023-11-04 11:14:41', '', '', NULL, NULL);

-- 
-- Dumping data for table payment
--

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;